server.port=8080
spring.application.name=ms-api
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# [0] ms-cliente (Módulo Principal)
spring.cloud.gateway.routes[0].id=ms-cliente
spring.cloud.gateway.routes[0].uri=lb://ms-cliente
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clientes/**

# [1] ms-cliente (Endpoints mudados de TipoCliente)
spring.cloud.gateway.routes[1].id=ms-tipocliente
spring.cloud.gateway.routes[1].uri=lb://ms-cliente
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tipo_cliente/**

# [2] ms-categorias
spring.cloud.gateway.routes[2].id=ms-categorias
spring.cloud.gateway.routes[2].uri=lb://ms-categorias
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/categorias/**

# [3] ms-detalleventas
spring.cloud.gateway.routes[3].id=ms-detalleventas
spring.cloud.gateway.routes[3].uri=lb://ms-detalleventas
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/detalleventas/**

# [4] ms-stock
spring.cloud.gateway.routes[4].id=ms-stock
spring.cloud.gateway.routes[4].uri=lb://ms-stock
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/stock/**

# [5] ms-prendas
spring.cloud.gateway.routes[5].id=ms-prendas
spring.cloud.gateway.routes[5].uri=lb://ms-prendas
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/prendas/**

# [6] ms-usuarios
spring.cloud.gateway.routes[6].id=ms-usuarios
spring.cloud.gateway.routes[6].uri=lb://ms-usuarios
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/usuarios/**

# [7] ms-perfil
spring.cloud.gateway.routes[7].id=ms-perfil
spring.cloud.gateway.routes[7].uri=lb://ms-perfil
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/perfiles/**

# [8] ms-empleados
spring.cloud.gateway.routes[8].id=ms-empleados
spring.cloud.gateway.routes[8].uri=lb://ms-empleados
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/empleados/**

# [9] ms-nominas
spring.cloud.gateway.routes[9].id=ms-nominas
spring.cloud.gateway.routes[9].uri=lb://ms-nominas
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/nominas/**

# [10] ms-envios
spring.cloud.gateway.routes[10].id=ms-envios
spring.cloud.gateway.routes[10].uri=lb://ms-envios
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/envios/**

# [11] ms-regiones
spring.cloud.gateway.routes[11].id=ms-regiones
spring.cloud.gateway.routes[11].uri=lb://ms-regiones
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/regiones/**

# [12] ms-sucursal
spring.cloud.gateway.routes[12].id=ms-sucursal
spring.cloud.gateway.routes[12].uri=lb://ms-sucursal
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/sucursales/**

# [13] ms-tiporopa
spring.cloud.gateway.routes[13].id=ms-tiporopa
spring.cloud.gateway.routes[13].uri=lb://ms-tiporopa
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/tiporopa/**

# [14] ms-ventas
spring.cloud.gateway.routes[14].id=ms-ventas
spring.cloud.gateway.routes[14].uri=lb://ms-ventas
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/ventas/**].predicates[0]=Path=/api/stock/**
spring.datasource.hikari.maximum-pool-size=2