spring.application.name=ms-sucursal
server.port=8089
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@wave6mvvwt38qrkd_high?TNS_ADMIN=C:/Users/Gamer/Desktop/WalletDeBaseDeDatos
spring.datasource.username=ADMIN
spring.datasource.password=FullStack-001
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.datasource.hikari.maximum-pool-size=2